name: CI	

on: [push, pull_request]	

jobs:	
  build:	

    runs-on: windows-2019	

    steps:	
    - uses: actions/checkout@v2	
      with:
        path: fde
    - uses: actions/checkout@v2	
      with:	
        path: flutter
        repository: flutter/flutter	
        ref: master	
        # Shallow clones don't work; see https://github.com/flutter/flutter/issues/18532
        fetch-depth: 0
    - name: Add Flutter tags
      # Add tags, which are also necessary for version checks to work.
      run: git fetch origin +refs/tags/*:refs/tags/*
      working-directory: ${{ github.workspace }}/flutter	
    - name: Add Flutter to path	
      run: echo "::add-path::$env:GITHUB_WORKSPACE\flutter\bin"	
    - name: Enable desktop support	
      run: |
        $Env:Path
        flutter config --enable-windows-desktop	
    - name: Build example debug	
      run: |	
        flutter packages get	
        flutter build -v windows --debug	
      working-directory: ${{ github.workspace }}/fde/example	
    - name: Build example release	
      run: |	
        flutter packages get	
        flutter build -v windows --release	
      working-directory: ${{ github.workspace }}/fde/example	
    - name: Build testbed debug	
      run: |	
        flutter packages get	
        flutter build -v windows --debug	
      working-directory: ${{ github.workspace }}/fde/testbed	
    - name: Build testbed release	
      run: |	
        flutter packages get	
        flutter build -v windows --release	
      working-directory: ${{ github.workspace }}/fde/testbed
